import { Component } from '@angular/core';
import { ObservabilityService } from './shared/observability.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  constructor(private observability: ObservabilityService) {
    observability.setup();
  }

  collectLogs() {
    console.info('in collectLogs');
    this.observability.faro.api.pushLog(['hello world']);
    this.observability.faro.api.pushEvent('click_collect_logs_button');
  }

  traceLogs() {

  }

  pushErrors() {
    const error = new Error('I am an error generated by network requests');
    this.observability.faro.api.pushError(error, {
      type: 'network',
    });
  }
}
