import { Component, AfterViewInit } from '@angular/core';
import { Faro, getWebInstrumentations, initializeFaro } from '@grafana/faro-web-sdk';
import { TracingInstrumentation } from '@grafana/faro-web-tracing';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  title = 'sample';
  faro!: Faro;

  ngAfterViewInit(): void {
    this.faro = initializeFaro({
      url: 'https://faro-collector-prod-ap-south-0.grafana.net/collect/a562f85cb6861cfa65c1c748ac3e0493',
      app: {
        name: 'angular-grafana-faro-test',
        version: '1.0.0',
        environment: 'production'
      },
      instrumentations: [
        // Mandatory, overwriting the instrumentations array would cause the default instrumentations to be omitted
        ...getWebInstrumentations({
          captureConsole: true,
          captureConsoleDisabledLevels: [],
        }),
    
        // Initialization of the tracing package.
        // This packages is optional because it increases the bundle size noticeably. Only add it if you want tracing data.
        new TracingInstrumentation({
          instrumentationOptions: {
            propagateTraceHeaderCorsUrls: [new RegExp('http://localhost:4200/*')],
          }
        }),
      ],
    });
  }

  tracing() {
    const otelApi = this.faro.api.getOTEL();
    if(otelApi) {
      const tracer = otelApi.trace.getTracer('default');
      const span = tracer.startSpan('click');
  
      otelApi.context.with(otelApi.trace.setSpan(otelApi.context.active(), span), () => {
        this.faro.api.pushLog(['tracing log']);
        span.end();
      });
    }
  }

  collectLogs() {
    console.info('in collectLogs');
    this.faro.api.pushLog(['hello world']);
    this.faro.api.pushEvent('click_collect_logs_button');
  }

  pushErrors() {
    const error = new Error('I am an error generated by network requests');
    this.faro.api.pushError(error, {
      type: 'network',
    });
  }
}
